### ISSUE TITLE
URGENT: Migrate all agents from GitHub Actions to Docker containers

### ISSUE THREAD

**Issue by jayo2005** [jayo2005/docker-mcp-servers#7]
## 🚨 Cost Alert: GitHub Actions Running Every 20 Minutes

We need to migrate all agents from GitHub Actions to Docker containers to eliminate costs.

### Current Situation
- Running workflows every 15-30 minutes across 7 repositories
- Using ~10,000+ minutes/month (5x free quota)
- Estimated cost: ~$65/month

#### Phase 1: Stop the Bleeding
I've already disabled scheduled workflows in paint-project-orchestration by renaming them to `.yml.disabled`

#### Phase 2: Docker Architecture
```
Docker Host
├── paint-sage-agent
├── paint-odoo-agent  
├── paint-tikkurila-agent
├── paint-project-manager
├── paint-woocommerce-agent
└── paint-mcp-coordinator
```

#### Phase 3: Implementation Guide

**1. Create Base Docker Image**
```dockerfile
FROM python:3.10-slim
WORKDIR /app
RUN pip install PyGithub requests python-dotenv
COPY requirements.txt .
RUN pip install -r requirements.txt
```

**2. Agent Container Example**
```dockerfile
FROM agent-base:latest
COPY agents/sage_extractor.py .
ENV GITHUB_TOKEN=${GITHUB_TOKEN}
CMD ["python", "-u", "sage_extractor.py"]
```

**3. Docker Compose Setup**
```yaml
version: '3.8'
services:
  sage-agent:
    build: ./paint-sage-operations
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: unless-stopped
    
  odoo-agent:
    build: ./paint-odoo-operations
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    restart: unless-stopped
```

**4. Agent Loop Pattern**
```python
import time
import os
from github import Github

def main():
    g = Github(os.environ['GITHUB_TOKEN'])
    repo = g.get_repo('jayo2005/paint-sage-operations')
    
    while True:
        print(f"Checking for issues at {datetime.now()}")
        
        # Check for new issues
        for issue in repo.get_issues(state='open'):
            # Process issue...
            pass
            
        # Sleep for 15 minutes
        time.sleep(900)

if __name__ == "__main__":
    main()
```

### Benefits
1. **Zero GitHub Actions costs**
2. **Instant agent responses** (no startup delay)
3. **Better logging** with `docker logs`
4. **Easy debugging** and updates
5. **Resource control** (CPU/memory limits)

### Testing Approach
1. Keep GitHub Actions as backup (disabled)
2. Run Docker agents in parallel
3. Compare results
4. Fully migrate once stable

### GitHub Issue Interface Unchanged
- Users still create issues in GitHub
- Agents still respond with comments
- Everything looks the same from user perspective

### Action Items
- [ ] Create Docker images for each agent
- [ ] Set up docker-compose.yml
- [ ] Test with one agent (suggest Sage)
- [ ] Roll out to all agents
- [ ] Document the setup

This is URGENT to stop the $65/month GitHub Actions costs!

---
*MCP Coordinator ready to help with Docker setup*
